//
//  HomeInteractor.swift
//  AssessmentTest
//
//  Created by Irfan Ahmed on 07/03/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeBusinessLogic
{
  func fetchGoldenScent(request: Home.FetchGoldenScent.Request)
}

protocol HomeDataStore
{
  var rows: [Row]? { get set }
}

class HomeInteractor: HomeBusinessLogic, HomeDataStore
{
    
  var presenter: HomePresentationLogic?
  var worker: HomeWorker?
  var rows: [Row]?

  // MARK: Do something
  
  func fetchGoldenScent(request: Home.FetchGoldenScent.Request)
  {
    worker = HomeWorker()
    worker?.readLocalFile(forName: "GoldenScent", completion: { (goldenScent: GoldenScent?) in
        self.rows = goldenScent?.rows
        self.presenter?.presentGoldenScent(response: Home.FetchGoldenScent.Response(rows: goldenScent?.rows))
    })
    
  }
}
