//
//  HomePresenter.swift
//  AssessmentTest
//
//  Created by Irfan Ahmed on 07/03/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic
{
  func presentGoldenScent(response: Home.FetchGoldenScent.Response)
}

class HomePresenter: HomePresentationLogic
{
  weak var viewController: HomeDisplayLogic?
  
  // MARK: Do something
  
  func presentGoldenScent(response: Home.FetchGoldenScent.Response)
  {
    let viewModel = Home.FetchGoldenScent.ViewModel(displayedRows: response.rows ?? [])
    viewController?.displayGoldenScent(viewModel: viewModel)
  }

}
