//
//  HomePageInteractor.swift
//  AssessmentTest
//
//  Created by Irfan Ahmed on 07/03/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePageBusinessLogic
{
  func fetchGoldenScent(request: HomePage.FetchGoldenScent.Request)
}

protocol HomePageDataStore
{
  var rows: [Row]? { get set }
}

class HomePageInteractor: HomePageBusinessLogic, HomePageDataStore
{
    
  var presenter: HomePagePresentationLogic?
  var worker: HomePageWorker?
  var rows: [Row]?

  // MARK: Do something
  
  func fetchGoldenScent(request: HomePage.FetchGoldenScent.Request)
  {
    worker = HomePageWorker()
    worker?.localDBManager.readLocalFile(forName: "GoldenScent", completion: { (goldenScent: GoldenScent?) in
        self.rows = goldenScent?.rows
        self.presenter?.presentGoldenScent(response: HomePage.FetchGoldenScent.Response(rows: rows))
    })
  }
}
