//
//  HomeModels.swift
//  AssessmentTest
//
//  Created by Irfan Ahmed on 07/03/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Home
{
  // MARK: Use cases
  
  enum FetchGoldenScent
  {
    struct Request
    {
    }
    struct Response
    {
        var rows: [Row]?
    }
    struct ViewModel
    {
        var displayedRows: [Row]

    }
  }
}
