//
//  HomePagePresenter.swift
//  AssessmentTest
//
//  Created by Irfan Ahmed on 07/03/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePagePresentationLogic
{
  func presentGoldenScent(response: HomePage.FetchGoldenScent.Response)
}

class HomePagePresenter: HomePagePresentationLogic
{
  weak var viewController: HomePageDisplayLogic?
  
  // MARK: Do something
  
  func presentGoldenScent(response: HomePage.FetchGoldenScent.Response)
  {
    let viewModel = HomePage.FetchGoldenScent.ViewModel(displayedRows: response.rows ?? [])
    viewController?.displayGoldenScent(viewModel: viewModel)
  }

}
